-- Fix workout types that were stored as numeric IDs instead of names
-- This is a one-time migration to correct data from before the workout type mapping fix

UPDATE ios_apple_health_workouts SET type = 'American Football' WHERE type = '1';
UPDATE ios_apple_health_workouts SET type = 'Archery' WHERE type = '2';
UPDATE ios_apple_health_workouts SET type = 'Australian Football' WHERE type = '3';
UPDATE ios_apple_health_workouts SET type = 'Badminton' WHERE type = '4';
UPDATE ios_apple_health_workouts SET type = 'Baseball' WHERE type = '5';
UPDATE ios_apple_health_workouts SET type = 'Basketball' WHERE type = '6';
UPDATE ios_apple_health_workouts SET type = 'Bowling' WHERE type = '7';
UPDATE ios_apple_health_workouts SET type = 'Boxing' WHERE type = '8';
UPDATE ios_apple_health_workouts SET type = 'Climbing' WHERE type = '9';
UPDATE ios_apple_health_workouts SET type = 'Cricket' WHERE type = '10';
UPDATE ios_apple_health_workouts SET type = 'Cross Training' WHERE type = '11';
UPDATE ios_apple_health_workouts SET type = 'Curling' WHERE type = '12';
UPDATE ios_apple_health_workouts SET type = 'Cycling' WHERE type = '13';
UPDATE ios_apple_health_workouts SET type = 'Dance' WHERE type = '14';
UPDATE ios_apple_health_workouts SET type = 'Elliptical' WHERE type = '16';
UPDATE ios_apple_health_workouts SET type = 'Equestrian Sports' WHERE type = '17';
UPDATE ios_apple_health_workouts SET type = 'Fencing' WHERE type = '18';
UPDATE ios_apple_health_workouts SET type = 'Fishing' WHERE type = '19';
UPDATE ios_apple_health_workouts SET type = 'Functional Strength Training' WHERE type = '20';
UPDATE ios_apple_health_workouts SET type = 'Golf' WHERE type = '21';
UPDATE ios_apple_health_workouts SET type = 'Gymnastics' WHERE type = '22';
UPDATE ios_apple_health_workouts SET type = 'Handball' WHERE type = '23';
UPDATE ios_apple_health_workouts SET type = 'Hiking' WHERE type = '24';
UPDATE ios_apple_health_workouts SET type = 'Hockey' WHERE type = '25';
UPDATE ios_apple_health_workouts SET type = 'Hunting' WHERE type = '26';
UPDATE ios_apple_health_workouts SET type = 'Lacrosse' WHERE type = '27';
UPDATE ios_apple_health_workouts SET type = 'Martial Arts' WHERE type = '28';
UPDATE ios_apple_health_workouts SET type = 'Mind and Body' WHERE type = '29';
UPDATE ios_apple_health_workouts SET type = 'Mixed Cardio' WHERE type = '30';
UPDATE ios_apple_health_workouts SET type = 'Paddle Sports' WHERE type = '31';
UPDATE ios_apple_health_workouts SET type = 'Play' WHERE type = '32';
UPDATE ios_apple_health_workouts SET type = 'Preparation and Recovery' WHERE type = '33';
UPDATE ios_apple_health_workouts SET type = 'Racquetball' WHERE type = '34';
UPDATE ios_apple_health_workouts SET type = 'Rowing' WHERE type = '35';
UPDATE ios_apple_health_workouts SET type = 'Rugby' WHERE type = '36';
UPDATE ios_apple_health_workouts SET type = 'Running' WHERE type = '37';
UPDATE ios_apple_health_workouts SET type = 'Sailing' WHERE type = '38';
UPDATE ios_apple_health_workouts SET type = 'Skating Sports' WHERE type = '39';
UPDATE ios_apple_health_workouts SET type = 'Snow Sports' WHERE type = '40';
UPDATE ios_apple_health_workouts SET type = 'Soccer' WHERE type = '41';
UPDATE ios_apple_health_workouts SET type = 'Softball' WHERE type = '42';
UPDATE ios_apple_health_workouts SET type = 'Squash' WHERE type = '43';
UPDATE ios_apple_health_workouts SET type = 'Stair Climbing' WHERE type = '44';
UPDATE ios_apple_health_workouts SET type = 'Surfing Sports' WHERE type = '45';
UPDATE ios_apple_health_workouts SET type = 'Swimming' WHERE type = '46';
UPDATE ios_apple_health_workouts SET type = 'Table Tennis' WHERE type = '47';
UPDATE ios_apple_health_workouts SET type = 'Tennis' WHERE type = '48';
UPDATE ios_apple_health_workouts SET type = 'Track and Field' WHERE type = '49';
UPDATE ios_apple_health_workouts SET type = 'Strength Training' WHERE type = '50';
UPDATE ios_apple_health_workouts SET type = 'Volleyball' WHERE type = '51';
UPDATE ios_apple_health_workouts SET type = 'Walking' WHERE type = '52';
UPDATE ios_apple_health_workouts SET type = 'Water Fitness' WHERE type = '53';
UPDATE ios_apple_health_workouts SET type = 'Water Polo' WHERE type = '54';
UPDATE ios_apple_health_workouts SET type = 'Water Sports' WHERE type = '55';
UPDATE ios_apple_health_workouts SET type = 'Wrestling' WHERE type = '56';
UPDATE ios_apple_health_workouts SET type = 'Yoga' WHERE type = '57';
UPDATE ios_apple_health_workouts SET type = 'Barre' WHERE type = '58';
UPDATE ios_apple_health_workouts SET type = 'Core Training' WHERE type = '59';
UPDATE ios_apple_health_workouts SET type = 'Cross Country Skiing' WHERE type = '60';
UPDATE ios_apple_health_workouts SET type = 'Downhill Skiing' WHERE type = '61';
UPDATE ios_apple_health_workouts SET type = 'Flexibility' WHERE type = '62';
UPDATE ios_apple_health_workouts SET type = 'High Intensity Interval Training' WHERE type = '63';
UPDATE ios_apple_health_workouts SET type = 'Jump Rope' WHERE type = '64';
UPDATE ios_apple_health_workouts SET type = 'Kickboxing' WHERE type = '65';
UPDATE ios_apple_health_workouts SET type = 'Pilates' WHERE type = '66';
UPDATE ios_apple_health_workouts SET type = 'Snowboarding' WHERE type = '67';
UPDATE ios_apple_health_workouts SET type = 'Stairs' WHERE type = '68';
UPDATE ios_apple_health_workouts SET type = 'Step Training' WHERE type = '69';
UPDATE ios_apple_health_workouts SET type = 'Wheelchair Walk Pace' WHERE type = '70';
UPDATE ios_apple_health_workouts SET type = 'Wheelchair Run Pace' WHERE type = '71';
UPDATE ios_apple_health_workouts SET type = 'Tai Chi' WHERE type = '72';
UPDATE ios_apple_health_workouts SET type = 'Mixed Cardio' WHERE type = '73';
UPDATE ios_apple_health_workouts SET type = 'Hand Cycling' WHERE type = '74';
UPDATE ios_apple_health_workouts SET type = 'Disc Sports' WHERE type = '75';
UPDATE ios_apple_health_workouts SET type = 'Fitness Gaming' WHERE type = '76';
UPDATE ios_apple_health_workouts SET type = 'Cardiodance' WHERE type = '77';
UPDATE ios_apple_health_workouts SET type = 'Social Dance' WHERE type = '78';
UPDATE ios_apple_health_workouts SET type = 'Pickleball' WHERE type = '79';
UPDATE ios_apple_health_workouts SET type = 'Cooldown' WHERE type = '80';
UPDATE ios_apple_health_workouts SET type = 'Swim Bike Run' WHERE type = '82';
UPDATE ios_apple_health_workouts SET type = 'Transition' WHERE type = '83';
UPDATE ios_apple_health_workouts SET type = 'Underwater Diving' WHERE type = '84';
UPDATE ios_apple_health_workouts SET type = 'Other' WHERE type = '3000';
